/**
 * AnswerScreen — Players type their answer; timer counts down; host sees live submission count
 */
import React, { useState, useEffect, useRef } from 'react';
import {
  View, Text, TextInput, TouchableOpacity, StyleSheet, SafeAreaView,
  KeyboardAvoidingView, Platform, Animated,
} from 'react-native';
import { useGameStore } from '../store/gameStore';
import { colors, spacing, radius, typography } from '../theme';

const TIMER_SECONDS = 45;

// Static AI-style commentary for demo
const AI_COMMENTARY = [
  "Wow. These answers reveal a group with truly exceptional taste... and one person who clearly needs more sleep.",
  "I processed all of your answers and I'm genuinely concerned about this team. In the best possible way.",
  "Statistically, one of these answers is a lie. I'm not saying which one. But I know.",
  "As an AI, I'm not supposed to have favourites. But I totally have a favourite. It's obviously the best one.",
  "These answers were generated by actual humans. I checked. Mostly.",
];

export default function AnswerScreen() {
  const { currentPrompt, roundIndex, players, fillDemoAnswers, showResults } = useGameStore();
  const [myAnswer, setMyAnswer] = useState('');
  const [submitted, setSubmitted] = useState(false);
  const [timeLeft, setTimeLeft] = useState(TIMER_SECONDS);
  const [submittedCount, setSubmittedCount] = useState(1); // host auto-submits
  const timerRef = useRef(null);
  const progressAnim = useRef(new Animated.Value(1)).current;

  useEffect(() => {
    // Animate progress bar
    Animated.timing(progressAnim, {
      toValue: 0,
      duration: TIMER_SECONDS * 1000,
      useNativeDriver: false,
    }).start();

    timerRef.current = setInterval(() => {
      setTimeLeft(t => {
        if (t <= 1) {
          clearInterval(timerRef.current);
          handleTimeUp();
          return 0;
        }
        // Simulate other players submitting
        setSubmittedCount(prev => {
          const maxPlayers = players.length;
          if (prev < maxPlayers && Math.random() < 0.3) return Math.min(prev + 1, maxPlayers);
          return prev;
        });
        return t - 1;
      });
    }, 1000);
    return () => clearInterval(timerRef.current);
  }, []);

  const handleTimeUp = () => {
    if (!submitted) {
      handleSubmit(myAnswer || '(no answer)');
    }
  };

  const handleSubmit = (answer) => {
    setSubmitted(true);
    clearInterval(timerRef.current);
    const text = answer || myAnswer || '(no answer)';
    fillDemoAnswers(text);
    // Short delay then show results with AI commentary
    setTimeout(() => {
      const commentary = AI_COMMENTARY[roundIndex % AI_COMMENTARY.length];
      showResults(commentary);
    }, 1500);
  };

  const barWidth = progressAnim.interpolate({
    inputRange: [0, 1], outputRange: ['0%', '100%'],
  });

  const timerColor = timeLeft > 15 ? colors.accent : timeLeft > 5 ? colors.warning : colors.error;

  return (
    <SafeAreaView style={styles.safe}>
      <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.flex}>
        <View style={styles.content}>
          {/* Timer bar */}
          <View style={styles.timerTrack}>
            <Animated.View style={[styles.timerBar, { width: barWidth, backgroundColor: timerColor }]} />
          </View>

          {/* Header */}
          <View style={styles.header}>
            <Text style={[styles.timer, { color: timerColor }]}>{timeLeft}s</Text>
            <Text style={styles.submitted}>{submittedCount}/{players.length} answered</Text>
          </View>

          {/* Prompt */}
          <View style={styles.promptCard}>
            <Text style={styles.prompt}>{currentPrompt}</Text>
          </View>

          {/* Answer input */}
          {submitted ? (
            <View style={styles.doneBox}>
              <Text style={styles.doneEmoji}>✅</Text>
              <Text style={styles.doneText}>Answer locked in!</Text>
              <Text style={styles.doneHint}>Waiting for everyone else...</Text>
            </View>
          ) : (
            <>
              <TextInput
                style={styles.input}
                placeholder="Type your answer..."
                placeholderTextColor={colors.textMuted}
                value={myAnswer}
                onChangeText={setMyAnswer}
                multiline
                numberOfLines={4}
                maxLength={280}
                autoFocus
              />
              <Text style={styles.charCount}>{myAnswer.length}/280</Text>
              <TouchableOpacity
                style={[styles.btn, !myAnswer.trim() && styles.btnDisabled]}
                disabled={!myAnswer.trim()}
                onPress={() => handleSubmit(myAnswer)}
              >
                <Text style={styles.btnText}>Lock In Answer</Text>
              </TouchableOpacity>
            </>
          )}
        </View>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe:         { flex: 1, backgroundColor: colors.bg },
  flex:         { flex: 1 },
  content:      { flex: 1, paddingTop: 0 },
  timerTrack:   { height: 4, backgroundColor: colors.card, width: '100%' },
  timerBar:     { height: 4 },
  header:       {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    paddingHorizontal: spacing.xl, paddingVertical: spacing.md,
  },
  timer:        { fontSize: 24, fontWeight: '800' },
  submitted:    { color: colors.textMuted, fontSize: 14 },
  promptCard:   {
    backgroundColor: colors.card, marginHorizontal: spacing.xl,
    borderRadius: radius.lg, padding: spacing.lg, marginBottom: spacing.lg,
    borderLeftWidth: 4, borderLeftColor: colors.primary,
  },
  prompt:       { ...typography.subhead, color: colors.text, lineHeight: 26 },
  input:        {
    backgroundColor: colors.card, borderWidth: 1, borderColor: colors.primary + '66',
    borderRadius: radius.md, padding: spacing.md,
    color: colors.text, fontSize: 16, minHeight: 120,
    marginHorizontal: spacing.xl, textAlignVertical: 'top',
  },
  charCount:    { color: colors.textMuted, fontSize: 12, textAlign: 'right', marginRight: spacing.xl, marginTop: 4 },
  btn:          {
    backgroundColor: colors.accent, borderRadius: radius.md,
    padding: spacing.md, alignItems: 'center',
    marginHorizontal: spacing.xl, marginTop: spacing.md,
  },
  btnDisabled:  { opacity: 0.4 },
  btnText:      { color: colors.white, fontSize: 17, fontWeight: '700' },
  doneBox:      { flex: 1, alignItems: 'center', justifyContent: 'center' },
  doneEmoji:    { fontSize: 64, marginBottom: spacing.md },
  doneText:     { ...typography.heading, color: colors.text, marginBottom: spacing.sm },
  doneHint:     { ...typography.body, color: colors.textSub },
});
